define(['jquery',
	'foundation/foundation',
	//'foundation/foundation.abide',
	//'foundation/foundation.alerts',
	//'foundation/foundation.clearing',
	//'foundation/foundation.cookie',
	//'foundation/foundation.dropdown',
	'foundation/foundation.forms',
	//'foundation/foundation.joyride',
	//'foundation/foundation.magellan',
	//'foundation/foundation.orbit',
	//'foundation/foundation.placeholder',
	'foundation/foundation.reveal',
	//'foundation/foundation.section',
	//'foundation/foundation.tooltips',
	//'foundation/foundation.topbar',
	//'foundation/foundation.interchange'
	], {});