FORMAT: 1A
HOST: http://quakemap.api.ushahidi.io/api/v3
-- HOST: http://dkiykvdirx.localtunnel.me/api/v3

# Ushahidi Platform API

Ushahidi is a tool to collect and manage citizen reports.

## Posts [/posts]

### List All Posts [GET]

+ Response 200 (application/json)

    + Attributes

        + count: 20
        + results (array[Post])
        + limit: 20 (string) --number
        + offset: 0 (string) --number
        + order: asc (string)
        + orderby: created (string)
        + curr: https://quakemap.api.ushahidi.io/api/v3/posts?offset=0&limit=20 (string)
        + next: https://quakemap.api.ushahidi.io/api/v3/posts?offset=20&limit=20 (string)
        + prev: https://quakemap.api.ushahidi.io/api/v3/posts?offset=0&limit=20 (string)
        + total_count: 100 (number)

### Get a Post [GET /posts/:id]

+ Response 200
+ Response 404

### Create a New Post [POST]

+ Request (application/json)

    + Attributes (Post)

+ Response 200 (application/json)

    + Attributes (Post)

+ Response 422

### Update a Post [PUT /posts/:id]

+ Response 422
+ Response 200
+ Response 404

### Delete a Post [DELETE /posts/:id]

+ Response 200
+ Response 404

## Tags [/tags]

### List All Tags [GET]

+ Response 200

### Create a Tag [POST]

+ Response 200

### Get a Tag [GET /tags/:id]

+ Response 200

### Update a Tag [PUT /tags/:id]

+ Response 200

### Delete a Tag [DELETE /tags/:id]

+ Response 200

## Collections [/collections]

### List All Collections [GET]

+ Response 200

### Create a Collection [POST]

+ Response 200

### Get a Collection [GET /tags/:id]

+ Response 200

### Update a Collection [PUT /tags/:id]

+ Response 200

### Delete a Collection [DELETE /tags/:id]

+ Response 200


## Collection Posts [/collections/:id/posts]

### Add a Post to a collection [POST]

+ Response 200

### Get a Post in a collection [GET]

+ Response 200


## Saved Searches [/savedsearches]

### List All [GET]

+ Response 200

### Create a Saved Search [POST]

+ Response 200

### Get a Saved Search [GET /savedsearches/:id]

+ Response 200

### Update a Saved Search [PUT /savedsearches/:id]

+ Response 200

### Delete a Saved Search [DELETE /savedsearches/:id]

+ Response 200


## Config [/config]

### List All Config Groups [GET]

+ Response 200

### Get a Config Group [GET /config/:id]

+ Response 200

### Update a Config Group [PUT /config/:id]

+ Response 200


## Data Providers [/dataproviders]

### List All Data Providers [GET]

+ Response 200

### Get a Data Provider [GET /dataproviders/:id]

+ Response 200


## Contacts [/contacts]

### List All Contacts [GET]

+ Response 200

### Create a Contacts [POST]

+ Response 200

### Get a Contacts [GET /contacts/:id]

+ Response 200

### Update a Contacts [PUT /contacts/:id]

+ Response 200

### Delete a Contacts [DELETE /contacts/:id]

+ Response 200


## Messages [/messages]

### List All Messages [GET]

+ Response 200

### Create a Message [POST]

+ Response 200

### Get a Message [GET /messages/:id]

+ Response 200

### Update a Message [PUT /messages/:id]

+ Response 200

### Delete a Message [DELETE /messages/:id]

+ Response 200


## Media [/media]

### List All Media [GET]

+ Response 200

### Create a Media [POST]

+ Response 200

### Get Media [GET /media/:id]

+ Response 200

### Update Media [PUT /media/:id]

+ Response 200

### Delete Media [DELETE /media/:id]

+ Response 200


## Users [/users]

### List All Users [GET]

+ Response 200

### Create a User [POST]

+ Response 200

### Get a User [GET /users/:id]

+ Response 200

### Update a User [PUT /users/:id]

+ Response 200

### Delete a User [DELETE /users/:id]

+ Response 200


## Roles [/roles]

### List All [GET]

+ Response 200

### Create a Role [POST]

+ Response 200

### Get a Role [GET /roles/:id]

+ Response 200

### Update a Role [PUT /roles/:id]

+ Response 200

### Delete a Role [DELETE /roles/:id]

+ Response 200


## Migrations [/migration]

### Get Migration Status [GET]

-- ### Migrate (unauthenticated) [GET /migrate]

+ Response 200 (application/json)

### Migrate [POST /migration/migrate]

+ Response 200 (application/json)


### Rollback [POST /migration/rollback]

+ Response 200 (application/json)

### Get Migration Status [GET /migration/status]

+ Response 200 (application/json)


## CSV [/csv]

### List All [GET]

+ Response 200 (application/json)

### Upload a CSV [POST]

+ Response 200 (application/json)

### Get CSV [GET /csv/:id]

+ Response 200 (application/json)

### Update CSV [PUT /csv/:id]

+ Response 200 (application/json)

### Delete CSV [DELETE /csv/:id]

+ Response 200 (application/json)

### Import a CSV [POST /csv/:id/import]

+ Response 200 (application/json)



# Group Forms

## Forms [/forms]

### List All Forms [GET]

+ Response 200 (application/json)


### Create a Form [POST]

+ Response 200 (application/json)


### Get a Form [GET /forms/:id]

+ Response 200 (application/json)


### Update a Form [PUT /forms/:id]

+ Response 200 (application/json)


### Delete a Form [DELETE /forms/:id]

+ Response 200 (application/json)



## Form Attributes [/forms/:formid/attributes]

### List All Form Attributes [GET]

+ Response 200 (application/json)


### Create a Form Attributes [POST]

+ Response 200 (application/json)


### Get a Form Attributes [GET /forms/:formid/attributes/:id]

+ Response 200 (application/json)


### Update a Form Attributes [PUT /forms/:formid/attributes/:id]

+ Response 200 (application/json)


### Delete a Form Attributes [DELETE /forms/:formid/attributes/:id]

+ Response 200 (application/json)



## Form Stages [/forms/:formid/stages]

### List All Form Stages [GET]

+ Response 200 (application/json)


### Create a Form Stage [POST]

+ Response 200 (application/json)


### Get a Form Stage [GET /forms/:formid/stages/:id]

+ Response 200 (application/json)


### Update a Form Stage [PUT /forms/:formid/stages/:id]

+ Response 200 (application/json)


### Delete a Form Stage [DELETE /forms/:formid/stages/:id]

+ Response 200 (application/json)



## Data Structures

### Post
+ id: 530 (number)
+ url: https://quakemap.api.ushahidi.io/api/v3/posts/530 (string)
+ parent_id: null (number)
+ title: Need help (required)
+ content: Asrang VDC of Gorkha hasn't received any help yet. Need relief efforts (required)
+ created: `2014-11-11T08:40:51+00:00`
+ updated: `2014-11-11T08:40:51+00:00`
+ form
    + id: 1
    + url: https://quakemap.api.ushahidi.io/api/v3/forms/1
+ user
    + id: 1
    + url: https://quakemap.api.ushahidi.io/api/v3/users/1
+ message
+ color: #2274B4 (string)
+ type: report (string)
+ slug: `chhokang-paro-village-upper-tsum-medical-ampamp-food-assistance-urgently-required-560b50a52fe02`
+ author_email: null
+ author_realname: null
+ status: published
+ locale: en_us
+ published_to (array)
+ completed_stages (array[number])
+ values (object)
+ tags (array)
    + (object)
      + id: 1 (number)
      + url: https://quakemap.api.ushahidi.io/api/v3/tags/1 (string)
+ sets: 1, 2 (array[string])
+ source: SMS (string)
+ contact
+ allowed_privileges: read, create (array[string])

