<?php defined('SYSPATH') or die('No direct access allowed.');

/**
 * SMSSync SMS provider
 */
class DataProvider_Smssync extends DataProvider {

	/**
	 * @return mixed
	 */
	public function send($to, $message)
	{
		// The SMSSync App on the phone will pick this SMS later for sending
		// For now just send back an autogenerated Tracking ID
		return $this->tracking_id('sms');
	}
}