<?php

namespace Ushahidi\App\DataSource\SMSSync;

/**
 * SMSSync Data Providers
 *
 * @author     Ushahidi Team <team@ushahidi.com>
 * @package    DataSource\SMSSync
 * @copyright  2013 Ushahidi
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License Version 3 (GPLv3)
 */

use Ushahidi\App\DataSource\DataSource;
use Ushahidi\App\DataSource\Message\Type as MessageType;
use Ushahidi\Core\Entity\Contact;
use Illuminate\Http\Request;

class SMSSync implements DataSource
{

	protected $config;

	/**
	 * Constructor function for DataSource
	 */
	public function __construct(array $config)
	{
		$this->config = $config;
	}

	public function getName()
    {
		return 'SMSSync';
	}

	public function getServices()
	{
		return [MessageType::SMS];
	}

	public function getOptions()
	{
		return array(
			'intro_step1' => array(
				'label' => 'Step 1: Download the "SMSSync" app from the Android Market.',
				'input' => 'read-only-text',
				'description' => function () {
					return 'Scan this QR Code with your phone to download the app from the Android Market
						<img src="'. url('/media/images/smssync.png') .'" width="150"/>';
				}
			),
			// @todo figure out how to inject link and fix base url
			'intro_step2' => array(
				'label' => 'Step 2: Android App Settings',
				'input' => 'read-only-text',
				'description' => function () {
					return 'Turn on SMSSync and use the following link as the Sync URL: ' . url('smssync');
				}
			),
			'secret' => array(
				'label' => 'Secret',
				'input' => 'text',
				'description' => 'Set a secret so that only authorized SMSSync devices can send/recieve message.
					You need to configure the same secret in the SMSSync App.',
				'rules' => array('required')
			)
		);
	}

	/**
	 * Contact type user for this provider
	 */
	public $contact_type = Contact::PHONE;

	/**
	 * @return mixed
	 */
	public function send($to, $message, $title = "")
	{
		// The SMSSync App on the phone will pick this SMS later for sending
		// For now just send back an autogenerated Tracking ID
		return array(DataSource\Message\Status::PENDING_POLL, $this->tracking_id(DataSource\Message\Type::SMS));
	}

	// DataSource
	public function fetch($limit = false)
    {
		return false;
	}

	// DataSource
	public function receive(Request $request)
    {
		return false;
	}

	// DataSource
	public function format($messages)
    {
		return false;
	}

	public function registerRoutes($app)
	{
		$app->post('sms/smssync', 'Ushahidi\App\DataSource\SMSSync\Controller\SMSSync@index');
		$app->post('smssync', 'Ushahidi\App\DataSource\SMSSync\Controller\SMSSync@index');
		$app->get('sms/smssync', 'Ushahidi\App\DataSource\SMSSync\Controller\SMSSync@index');
		$app->get('smssync', 'Ushahidi\App\DataSource\SMSSync\Controller\SMSSync@index');
	}

	public function verifySecret($secret)
	{
		if (isset($this->config['secret']) and $secret === $this->config['secret']) {
			return true;
		}

		return false;
	}
}
