<?php

namespace Ushahidi\App\DataSource\SMSSync;

/**
 * SMSSync Data Providers
 *
 * @author     Ushahidi Team <team@ushahidi.com>
 * @package    DataSource\SMSSync
 * @copyright  2013 Ushahidi
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License Version 3 (GPLv3)
 */

use Ushahidi\App\DataSource\DataSource;
use Ushahidi\Core\Entity\Contact;

class SMSSync extends DataSource {

	/**
	 * Contact type user for this provider
	 */
	public $contact_type = Contact::PHONE;

	/**
	 * @return mixed
	 */
	public function send($to, $message, $title = "")
	{
		// The SMSSync App on the phone will pick this SMS later for sending
		// For now just send back an autogenerated Tracking ID
		return array(DataSource\Message\Status::PENDING_POLL, $this->tracking_id(DataSource\Message\Type::SMS));
	}

}
