
# Group Collections

## Collections [/api/v3/collections]

### List All Collections [GET]

+ Response 200

### Create a Collection [POST]

+ Response 200

### Get a Collection [GET /api/v3/collections/{id}]

+ Response 200

### Update a Collection [PUT /api/v3/collections/{id}]

+ Response 200

### Delete a Collection [DELETE /api/v3/collections/{id}]

+ Response 200


## Collection Posts [/api/v3/collections/{id}/posts]

### Add a Post to a collection [POST]

+ Response 200

### Get a Post in a collection [GET]

+ Response 200

# Group Saved Searches

## Saved Searches [/api/v3/savedsearches]

### List All [GET]

+ Response 200
