
# Group Config

## Config [/api/v3/config]

### List All Config Groups [GET]

+ Response 200

### Get a Config Group [GET /api/v3/config/{id}]

+ Response 200

### Update a Config Group [PUT /api/v3/config/{id}]

+ Response 200
