
# Group Forms

## Forms [/api/v3/forms]

### List All Forms [GET]

+ Response 200 (application/json)


### Create a Form [POST]

+ Response 200 (application/json)


### Get a Form [GET /api/v3/forms/{id}]

+ Response 200 (application/json)


### Update a Form [PUT /api/v3/forms/{id}]

+ Response 200 (application/json)


### Delete a Form [DELETE /api/v3/forms/{id}]

+ Response 200 (application/json)



## Form Attributes [/api/v3/forms/{formid}/attributes]

### List All Form Attributes [GET]

+ Response 200 (application/json)


### Create a Form Attributes [POST]

+ Response 200 (application/json)


### Get a Form Attributes [GET /api/v3/forms/{formid}/attributes/{id}]

+ Response 200 (application/json)


### Update a Form Attributes [PUT /api/v3/forms/{formid}/attributes/{id}]

+ Response 200 (application/json)


### Delete a Form Attributes [DELETE /api/v3/forms/{formid}/attributes/{id}]

+ Response 200 (application/json)



## Form Stages [/api/v3/forms/{formid}/stages]

### List All Form Stages [GET]

+ Response 200 (application/json)


### Create a Form Stage [POST]

+ Response 200 (application/json)


### Get a Form Stage [GET /api/v3/forms/{formid}/stages/{id}]

+ Response 200 (application/json)


### Update a Form Stage [PUT /api/v3/forms/{formid}/stages/{id}]

+ Response 200 (application/json)


### Delete a Form Stage [DELETE /api/v3/forms/{formid}/stages/{id}]

+ Response 200 (application/json)
