

# Group Import

## CSV [/api/v3/csv]

### List All [GET]

+ Response 200 (application/json)

### Upload a CSV [POST]

+ Response 200 (application/json)

### Get CSV [GET /api/v3/csv/{id}]

+ Response 200 (application/json)

### Update CSV [PUT /api/v3/csv/{id}]

+ Response 200 (application/json)

### Delete CSV [DELETE /api/v3/csv/{id}]

+ Response 200 (application/json)

### Import a CSV [POST /api/v3/csv/{id}/import]

+ Response 200 (application/json)

