# Group Messages & Contacts

## Messages [/api/v3/messages]

### List All Messages [GET]

+ Response 200

### Create a Message [POST]

+ Response 200

### Get a Message [GET /api/v3/messages/{id}]

+ Response 200

### Update a Message [PUT /api/v3/messages/{id}]

+ Response 200

### Delete a Message [DELETE /api/v3/messages/{id}]

+ Response 200

## Contacts [/api/v3/contacts]

### List All Contacts [GET]

+ Response 200

### Create a Contacts [POST]

+ Response 200

### Get a Contacts [GET /api/v3/contacts/{id}]

+ Response 200

### Update a Contacts [PUT /api/v3/contacts/{id}]

+ Response 200

### Delete a Contacts [DELETE /api/v3/contacts/{id}]

+ Response 200
