
### Create a Saved Search [POST]

+ Response 200

### Get a Saved Search [GET /api/v3/savedsearches/{id}]

+ Response 200

### Update a Saved Search [PUT /api/v3/savedsearches/{id}]

+ Response 200

### Delete a Saved Search [DELETE /api/v3/savedsearches/{id}]

+ Response 200
