# Group Tags

### List All Tags [GET /api/v3/tags{?q}]

+ Parameters

    + q

+ Response 200

### Create a Tag [POST /api/v3/tags]

+ Response 200

## Individual Tag [/api/v3/tags/{id}]

### Get a Tag [GET]

+ Parameters

    + id (number) - ID of the Tag

+ Response 200

### Update a Tag [PUT]

+ Response 200

### Delete a Tag [DELETE]

+ Response 200
