
# Group Users & Roles

## Users [/api/v3/users]

### List All Users [GET]

+ Response 200

### Create a User [POST]

+ Response 200

### Get a User [GET /api/v3/users/{id}]

+ Response 200

### Update a User [PUT /api/v3/users/{id}]

+ Response 200

### Delete a User [DELETE /api/v3/users/{id}]

+ Response 200


## Roles [/api/v3/roles]

### List All [GET]

+ Response 200

### Create a Role [POST]

+ Response 200

### Get a Role [GET /api/v3/roles/{id}]

+ Response 200

### Update a Role [PUT /api/v3/roles/{id}]

+ Response 200

### Delete a Role [DELETE /api/v3/roles/{id}]

+ Response 200

